robot:
  wheel_radius: 0.027216 # radius of the large wheels in meters
  width:  0.143 # measure the wheel-to-wheel width of your robot and put it here. It is also in meters (so 0.2 = 20cm)
  delta_t: 0.15 # in seconds

camera:
  #y_offset: -0.05 # where is the camera in relation to the robot's centre
  #z_offset: 0.27 # where is the camera in relation to the robot's centre
  #x_angle: -131 # in radians. 0 would mean that the robot is looking straight up, 90° means that the camera is pointing forward parallel to the floor.
  y_offset: 0.0
  z_offset: 0.28
  x_angle: -126.5
  exposure_time: 80
  gain: 50

ekf_slam:
  robot_width: 0.143 # measure the wheel-to-wheel width of your robot and put it here. It is also in meters (so 0.2 = 20cm)
  motor_std: 4 # std = standard deviation. You might need to adjust these values depending on your motors, robot construction etc.
  dist_std: 0.1 # std = standard deviation. You might need to adjust these values depending on your motors, robot construction etc.
  angle_std: 4 # std = standard deviation. You might need to adjust these values depending on your motors, robot construction etc.
blocks:
  count: 4
pid_controller:
  P: 8
  I: 0
  D: 0
